export type CertificateCategory =
  | "ai-ml"
  | "programming-web"
  | "marketing-design"
  | "engineering-energy"
  | "management-leadership"
  | "global-health-safety";

export type CertificatePlatform =
  | "Coursera"
  | "edX"
  | "Stepik"
  | "Harvard"
  | "IBM"
  | "Google"
  | "Yandex"
  | "Netology"
  | "GeekBrains"
  | "UN / WHO"
  | "Other";

export type EducationCertificate = {
  id: string;
  title: string;
  titleRu?: string;
  issuer: string;
  platform: CertificatePlatform;
  category: CertificateCategory;
  year?: number | string;
  url: string;
  credentialId?: string;
  skills: readonly string[];
  isFlagship?: boolean;
  isSpecialization?: boolean;
  coursesCount?: number;
};

export const CATEGORY_LABELS: Record<CertificateCategory, { label: string; icon: string }> = {
  "ai-ml": { label: "Искусственный интеллект & ML", icon: "🤖" },
  "programming-web": { label: "Программирование & Веб", icon: "💻" },
  "marketing-design": { label: "Маркетинг, Аналитика & Дизайн", icon: "📈" },
  "engineering-energy": { label: "Энергетика, Инженерия & Lean", icon: "⚡" },
  "management-leadership": { label: "Менеджмент & Лидерство", icon: "🏛️" },
  "global-health-safety": { label: "ООН, ВОЗ, Медицина & Безопасность", icon: "🌍" },
};

export const formalEducationList = [
  {
    id: "mgkso",
    title: "Минский государственный колледж сферы обслуживания (МГКСО)",
    qualification: "Техник-электромеханик",
    specialty: "Электрооборудование, киноустановки и аудиовизуальные комплексы",
    years: "2009–2013",
    type: "Государственный диплом",
    description: "Базовое инженерно-техническое образование: физика цепей, электромеханика, звукотехнические и кинопроекционные комплексы, монтаж и диагностика систем.",
    verified: true,
  },
  {
    id: "minskvodokanal",
    title: "УП «Минскводоканал» // ГЦПК «ЖИЛКОМ»",
    qualification: "Электромонтер 5-го разряда",
    specialty: "Ремонт и обслуживание электрооборудования (до и выше 1000В, IV группа допуска)",
    years: "2014–2021 (7 лет стажа)",
    type: "Государственное свидетельство",
    description: "7 лет ежедневной практической работы с распределительными подстанциями, электродвигателями, автоматикой управления и высоковольтными силовыми цепями.",
    verified: true,
  },
  {
    id: "rcttu",
    title: "Республиканский Центр технического творчества учащихся (РЦТТУ)",
    qualification: "Пользователь ПЭВМ, программист Turbo Pascal",
    specialty: "Программирование на Turbo Pascal 7.0, сети, веб-сайты, ремонт и тестирование ПК, CorelDRAW, Photoshop",
    years: "2005–2009",
    type: "Официальная характеристика и свидетельства",
    description: "Ранняя алгоритмическая и компьютерная школа: архитектура железа, низкоуровневая логика, верстка первых сайтов и растровая/векторная графика.",
    verified: true,
  },
] as const;

export const educationCertificates: readonly EducationCertificate[] = [
  // -------------------------------------------------------------
  // 1. ИСКУССТВЕННЫЙ ИНТЕЛЛЕКТ & ML (ai-ml)
  // -------------------------------------------------------------
  {
    id: "ai-vanderbilt-prompt-spec",
    title: "Prompt Engineering Specialization",
    titleRu: "Специализация: Промпт-инжиниринг для генеративных моделей",
    issuer: "Vanderbilt University (Университет Вандербильта)",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/specialization/75BAPX4WBTMY",
    isFlagship: true,
    isSpecialization: true,
    coursesCount: 3,
    skills: ["Prompt Engineering", "ChatGPT", "Advanced Data Analysis", "Trustworthy AI"],
  },
  {
    id: "ai-vanderbilt-chatgpt",
    title: "Prompt Engineering for ChatGPT",
    titleRu: "Оперативное проектирование и промптинг для ChatGPT",
    issuer: "Vanderbilt University",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/GFVV7DKAU44Z",
    skills: ["ChatGPT", "Few-Shot Prompting", "Chain of Thought"],
  },
  {
    id: "ai-vanderbilt-data-analysis",
    title: "ChatGPT Advanced Data Analysis",
    titleRu: "Расширенный анализ данных с помощью ChatGPT",
    issuer: "Vanderbilt University",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/UDTWQ42UCSA7",
    skills: ["Python Data Analysis", "Code Interpreter", "Automated Reporting"],
  },
  {
    id: "ai-vanderbilt-trustworthy",
    title: "Trustworthy Generative AI",
    titleRu: "Надежный и безопасный генеративный ИИ",
    issuer: "Vanderbilt University",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/KH63FPEENTNR",
    skills: ["AI Safety", "Hallucination Mitigation", "Robust Workflows"],
  },
  {
    id: "ai-vanderbilt-gpts",
    title: "OpenAI GPTs: Creating Your Own Custom AI Assistants",
    titleRu: "Создание пользовательских ИИ-помощников в OpenAI GPTs",
    issuer: "Vanderbilt University",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/UFZLP3EQ7YU7",
    isFlagship: true,
    skills: ["Custom GPTs", "Action API", "System Knowledge Bases"],
  },
  {
    id: "ai-ibm-genai-spec",
    title: "Generative AI Fundamentals Specialization",
    titleRu: "Специализация: Основы генеративного искусственного интеллекта",
    issuer: "IBM",
    platform: "IBM",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/specialization/N3JPRDE8AHUE",
    isFlagship: true,
    isSpecialization: true,
    coursesCount: 5,
    skills: ["Generative AI", "Foundation Models", "LLM Platforms", "Enterprise AI"],
  },
  {
    id: "ai-ibm-prompt-basics",
    title: "Generative AI: Prompt Engineering Basics",
    titleRu: "Основы проектирования подсказок для генеративного ИИ",
    issuer: "IBM",
    platform: "IBM",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/MRUCLTRNEE9Z",
    skills: ["Prompt Patterns", "Tokenization", "LLM Steering"],
  },
  {
    id: "ai-ibm-intro-applications",
    title: "Generative AI: Introduction and Applications",
    titleRu: "Генеративный искусственный интеллект: введение и применение",
    issuer: "IBM",
    platform: "IBM",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/DCBEX7W8NZXW",
    skills: ["AI Applications", "Workflow Integration", "Generative Vision"],
  },
  {
    id: "ai-ibm-foundation-models",
    title: "Generative AI: Foundation Models and Platforms",
    titleRu: "Базовые модели и платформы генеративного ИИ",
    issuer: "IBM",
    platform: "IBM",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/NB4PSEAWV4R5",
    skills: ["Transformer Architecture", "Hugging Face", "IBM watsonx"],
  },
  {
    id: "ai-ibm-fine-tuning",
    title: "Generative AI Advance Fine-Tuning for LLMs",
    titleRu: "Тонкая настройка (Fine-Tuning) больших языковых моделей",
    issuer: "IBM",
    platform: "IBM",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/FV2BFCNYJTG8",
    isFlagship: true,
    skills: ["LoRA", "PEFT", "Instruction Tuning", "Model Alignment"],
  },
  {
    id: "ai-ibm-impact-ethics",
    title: "Generative AI: Impact, Considerations, and Ethical Issues",
    titleRu: "Этика, влияние и социальные аспекты генеративного ИИ",
    issuer: "IBM",
    platform: "IBM",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/2K4USV2RSHVX",
    skills: ["AI Governance", "Bias Detection", "Intellectual Property"],
  },
  {
    id: "ai-ibm-intro-ai",
    title: "Introduction to Artificial Intelligence (AI)",
    titleRu: "Введение в искусственный интеллект",
    issuer: "IBM",
    platform: "IBM",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/ZCYKQSZFTA30",
    skills: ["AI Foundations", "Cognitive Computing", "IBM Watson"],
  },
  {
    id: "ai-google-ai-essentials",
    title: "Google AI Essentials",
    titleRu: "Основы искусственного интеллекта от Google",
    issuer: "Google",
    platform: "Google",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/ED35K9D93X2L",
    isFlagship: true,
    skills: ["Gemini", "Multimodal AI", "Productivity Automation", "AI Workflows"],
  },
  {
    id: "ai-google-fundamentals",
    title: "AI Fundamentals",
    titleRu: "Базовые принципы и концепции ИИ",
    issuer: "Google",
    platform: "Google",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/2SCOC8OZT9PU",
    skills: ["Machine Learning", "Neural Networks", "Google Cloud AI"],
  },
  {
    id: "ai-intel-ai-fundamentals",
    title: "Intel® AI Fundamentals Specialization",
    titleRu: "Специализация: Основы Intel® AI",
    issuer: "Intel",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/specialization/4VKDRUMUG99N",
    isFlagship: true,
    isSpecialization: true,
    coursesCount: 3,
    skills: ["Hardware Acceleration", "Intel OpenVINO", "Edge AI", "Model Optimization"],
  },
  {
    id: "ai-huggingface-agents",
    title: "AI Agents Fundamentals",
    titleRu: "Основы автономных ИИ-агентов",
    issuer: "Hugging Face",
    platform: "Other",
    category: "ai-ml",
    url: "https://cdn-lfs-us-1.hf.co/repos/f2/34/f2344151f60f6027c436821dc61cf3f27a46435de57df8df50ad02b5acca7c07/4c81fd9ddc2033e7900275a483dd9092d0e08abd7f90d819876d33ca1158c283",
    isFlagship: true,
    skills: ["Autonomous Agents", "Tool Calling", "ReAct Loops", "smolagents"],
  },
  {
    id: "ai-anthropic-claude-code",
    title: "Claude Code in Action",
    titleRu: "Claude Code в действии: агентное программирование",
    issuer: "Anthropic Academy",
    platform: "Other",
    category: "ai-ml",
    url: "https://verify.skilljar.com/c/mcgx5qh4hpej",
    isFlagship: true,
    skills: ["Claude Code", "Agentic Coding", "Terminal Workflows", "Vibe Coding"],
  },
  {
    id: "ai-uc-davis-multiagent",
    title: "AI Agents: From Prompts to Multi-Agent Systems",
    titleRu: "ИИ-агенты: от промптов к многоагентным системам",
    issuer: "University of California, Davis",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/EVVOCIMERRR5",
    isFlagship: true,
    skills: ["Multi-Agent Architecture", "Task Orchestration", "Agentic Frameworks"],
  },
  {
    id: "ai-babson-leaders",
    title: "AI for Leaders",
    titleRu: "Искусственный интеллект для лидеров и руководителей",
    issuer: "Babson College (Колледж Бэбсон)",
    platform: "edX",
    category: "ai-ml",
    url: "https://courses.edx.org/certificates/8ce8d215a02344a38bce221f54845009",
    skills: ["Executive AI", "Strategic Deployment", "AI Transformation"],
  },
  {
    id: "ai-helsinki-elements",
    title: "Elements of AI",
    titleRu: "Элементы искусственного интеллекта",
    issuer: "University of Helsinki",
    platform: "Other",
    category: "ai-ml",
    url: "https://certificates.mooc.fi/validate/mu6fincpf3",
    skills: ["AI Theory", "Bayesian Logic", "Ethics in AI"],
  },
  {
    id: "ai-glasgow-gpt",
    title: "Generative Pre-trained Transformers (GPT)",
    titleRu: "Архитектура генеративных предобученных трансформеров",
    issuer: "University of Glasgow",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/T6Z8BK6LZSDF",
    skills: ["Attention Mechanisms", "Transformer Math", "Autoregressive Models"],
  },
  {
    id: "ai-palermo-prompts",
    title: "Inteligencia Artificial: Interacciones y prompts",
    titleRu: "Искусственный интеллект: взаимодействие и сценарии подсказок",
    issuer: "Universidad de Palermo",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/PN8AZVJZ96VJ",
    skills: ["Prompt Interaction", "Context Windows", "LLM Workflows"],
  },
  {
    id: "ai-adobe-content",
    title: "Generative AI Content Creation",
    titleRu: "Создание контента с помощью генеративного ИИ",
    issuer: "Adobe",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/B6X5HFIRROUV",
    skills: ["Adobe Firefly", "Generative Fill", "Commercial AI Art"],
  },
  {
    id: "ai-certnexus-problems",
    title: "Solve Business Problems with AI and Machine Learning",
    titleRu: "Решение бизнес-задач с помощью ИИ и машинного обучения",
    issuer: "CertNexus",
    platform: "Coursera",
    category: "ai-ml",
    url: "https://www.coursera.org/account/accomplishments/verify/AO7OD79PX22Y",
    skills: ["Business ML", "Predictive Analytics", "Problem Scoping"],
  },
  {
    id: "ai-fefu-law-ethics",
    title: "Право и этика искусственного интеллекта",
    titleRu: "Правовое регулирование и этические стандарты в ИИ",
    issuer: "Дальневосточный федеральный университет (ДВФУ)",
    platform: "Stepik",
    category: "ai-ml",
    url: "https://stepik.org/certificate/f2da5f5bd4d50fc7285c018eb3f032f5dbfee005.pdf",
    skills: ["Право ИИ", "Авторские права в нейросетях", "Этика алгоритмов"],
  },
  {
    id: "ai-learnprompting",
    title: "ChatGPT for Everyone",
    titleRu: "Практический ChatGPT для всех",
    issuer: "Learn Prompting",
    platform: "Other",
    category: "ai-ml",
    url: "https://learnprompting.thinkific.com/certificates/qnpk5lx7ga",
    skills: ["Prompt Basics", "Practical Automation", "Everyday AI Tools"],
  },

  // -------------------------------------------------------------
  // 2. ПРОГРАММИРОВАНИЕ & ВЕБ (programming-web)
  // -------------------------------------------------------------
  {
    id: "tech-harvard-cs50",
    title: "CS50 Technology",
    titleRu: "CS50: Основы компьютерных технологий и программирования",
    issuer: "Harvard University (Гарвардский университет)",
    platform: "Harvard",
    category: "programming-web",
    url: "https://certificates.cs50.io/8dfb8570-aa39-48e8-936a-68a64b8babad.pdf?size=letter",
    isFlagship: true,
    skills: ["Computer Science", "Algorithms", "Web Architecture", "Hardware Foundations"],
  },
  {
    id: "tech-cisco-it-essentials",
    title: "IT Essentials: PC Hardware and Software",
    titleRu: "IT Essentials: Аппаратное и программное обеспечение ПК",
    issuer: "Cisco Networking Academy / МГКСО",
    platform: "Other",
    category: "programming-web",
    url: "https://drive.google.com/file/d/1lZWjZBcKh4swUuZYejaetvZioTgoDHMR/view?usp=sharing",
    isFlagship: true,
    skills: ["Hardware Assembly", "OS Troubleshooting", "Network Configuration"],
  },
  {
    id: "tech-rcttu-pascal",
    title: "Программирование на языке Turbo Pascal 7.0 & Сети",
    titleRu: "Turbo Pascal 7.0, Архитектура ПК, Веб-сайты и Компьютерная графика",
    issuer: "РЦТТУ (Республиканский центр тех. творчества учащихся)",
    platform: "Other",
    category: "programming-web",
    url: "https://drive.google.com/file/d/1_9rtU15W4358uqK4GAyqdplFVYmi52L7/view?usp=sharing",
    isFlagship: true,
    skills: ["Turbo Pascal 7.0", "HTML", "CorelDRAW", "Photoshop", "Hardware Diagnostics"],
  },
  {
    id: "tech-hackerrank-csharp",
    title: "C# (Basic) Certificate",
    titleRu: "Сертификация базового владения C#",
    issuer: "HackerRank",
    platform: "Other",
    category: "programming-web",
    url: "https://www.hackerrank.com/certificates/iframe/3e1d77b8b9b5",
    skills: ["C#", "OOP", "Data Structures"],
  },
  {
    id: "tech-ibm-tech-support",
    title: "IBM Technical Support Professional Certificate",
    titleRu: "Профессиональный сертификат: Техническая поддержка IBM",
    issuer: "IBM",
    platform: "IBM",
    category: "programming-web",
    url: "https://www.coursera.org/account/accomplishments/professional-cert/JZKBUASAEK3H",
    isFlagship: true,
    isSpecialization: true,
    skills: ["IT Support", "Operating Systems", "Cloud Foundations", "Networking"],
  },
  {
    id: "tech-ibm-hardware-os",
    title: "Introduction to Hardware and Operating Systems",
    titleRu: "Введение в аппаратное обеспечение и операционные системы",
    issuer: "IBM",
    platform: "IBM",
    category: "programming-web",
    url: "https://www.coursera.org/account/accomplishments/verify/RF4BHQHPYZMU",
    skills: ["OS Kernel Basics", "System Architecture", "Troubleshooting"],
  },
  {
    id: "tech-ibm-software-db",
    title: "Introduction to Software, Programming, and Databases",
    titleRu: "Введение в программное обеспечение, программирование и БД",
    issuer: "IBM",
    platform: "IBM",
    category: "programming-web",
    url: "https://www.coursera.org/account/accomplishments/verify/NFTM6R6Q7372",
    skills: ["Databases", "SQL Basics", "Software Architecture"],
  },
  {
    id: "tech-ibm-cloud",
    title: "Introduction to Cloud Computing",
    titleRu: "Введение в облачные вычисления (IBM Cloud Badge)",
    issuer: "IBM",
    platform: "IBM",
    category: "programming-web",
    url: "https://www.coursera.org/account/accomplishments/verify/E7URHZ7MAZKY",
    skills: ["Cloud Architecture", "IaaS / PaaS / SaaS", "Virtualization"],
  },
  {
    id: "tech-ibm-cybersecurity",
    title: "Introduction to Cybersecurity Essentials",
    titleRu: "Основы кибербезопасности (Credly Badge)",
    issuer: "IBM",
    platform: "IBM",
    category: "programming-web",
    url: "https://www.coursera.org/account/accomplishments/verify/PPBPHGTB6ETL",
    skills: ["Cyber Threat Defense", "Encryption", "Security Protocols"],
  },
  {
    id: "tech-google-support",
    title: "Technical Support Fundamentals",
    titleRu: "Основы технической поддержки Google",
    issuer: "Google",
    platform: "Google",
    category: "programming-web",
    url: "https://www.coursera.org/account/accomplishments/certificate/V66XMJ8B32Q3",
    skills: ["Customer Support", "Linux CLI", "Troubleshooting"],
  },
  {
    id: "tech-google-networking",
    title: "The Bits and Bytes of Computer Networking",
    titleRu: "Биты и байты компьютерных сетей",
    issuer: "Google",
    platform: "Google",
    category: "programming-web",
    url: "https://www.coursera.org/account/accomplishments/verify/R4WHTK6FGK59",
    skills: ["TCP/IP", "DNS", "Subnetting", "Routing"],
  },
  {
    id: "tech-stepik-html-css",
    title: "Основы HTML & CSS",
    titleRu: "Верстка веб-страниц: основы HTML5 и CSS3",
    issuer: "Stepik",
    platform: "Stepik",
    category: "programming-web",
    url: "https://stepik.org/certificate/0209a04225a1ffc2a45bc1aa6fe018154a1bca56.pdf",
    skills: ["HTML5", "CSS3", "Семантическая верстка"],
  },
  {
    id: "tech-itc-html-css",
    title: "Веб-разработка для начинающих: HTML и CSS",
    titleRu: "Практическая веб-разработка",
    issuer: "ITC / Stepik",
    platform: "Stepik",
    category: "programming-web",
    url: "https://stepik.org/certificate/c9f9c84fd75abe0305a22052cdaaf37d54ccc999.pdf",
    skills: ["Flexbox", "Responsive Design", "Web Forms"],
  },
  {
    id: "tech-fefu-cybersec",
    title: "Введение в кибербезопасность",
    titleRu: "Основы информационной безопасности и защиты данных",
    issuer: "Дальневосточный федеральный университет (ДВФУ)",
    platform: "Stepik",
    category: "programming-web",
    url: "https://stepik.org/certificate/18127f26e5fe450f3238c9e49b24abb4cc2afca3.pdf",
    skills: ["Информационная безопасность", "Аудит уязвимостей", "Криптография"],
  },
  {
    id: "tech-fefu-networking",
    title: "Введение в сетевые технологии",
    titleRu: "Сетевые протоколы, маршрутизация и коммутация",
    issuer: "Дальневосточный федеральный университет (ДВФУ)",
    platform: "Stepik",
    category: "programming-web",
    url: "https://stepik.org/certificate/eaf01dd531a2c41a3f50ab760cdd0bab83397c92.pdf",
    skills: ["Сетевые модели OSI/TCP", "Маршрутизация", "IP-адресация"],
  },
  {
    id: "tech-bitrix-content",
    title: "1С-Битрикс: Контент-менеджер",
    titleRu: "Администрирование и наполнение сайтов на 1С-Битрикс",
    issuer: "ООО «1С-Битрикс»",
    platform: "Other",
    category: "programming-web",
    url: "https://drive.google.com/file/d/1XHhoWVBVmZwJ3OYgQGEjXa0wV0VfCENt/view?usp=sharing",
    skills: ["1С-Битрикс", "Управление контентом", "Структура инфоблоков"],
  },
  {
    id: "tech-bitrix-marketing",
    title: "1С-Битрикс: Продвижение сайта и Маркетинг",
    titleRu: "SEO и маркетинговые инструменты платформы 1С-Битрикс",
    issuer: "ООО «1С-Битрикс»",
    platform: "Other",
    category: "programming-web",
    url: "https://drive.google.com/file/d/1Q7jp6VLH2bu9Wce5t_gT73-Ju784-FVU/view?usp=sharing",
    skills: ["Bitrix SEO", "E-commerce Маркетинг", "Конверсионные формы"],
  },
  {
    id: "tech-bitrix-multisite",
    title: "1С-Битрикс: Многосайтовость",
    titleRu: "Развертывание и управление несколькими сайтами на одной CMS",
    issuer: "ООО «1С-Битрикс»",
    platform: "Other",
    category: "programming-web",
    url: "https://drive.google.com/file/d/1vbcIVYo6s4jjPUKzyusqyA3BYAjSiW8g/view?usp=sharing",
    skills: ["Мультидоменность", "Конфигурация ядра", "Многосайтовость"],
  },
  {
    id: "tech-geekbrains-prog",
    title: "Основы программирования",
    titleRu: "Алгоритмизация и структуры данных",
    issuer: "Образовательная платформа GeekBrains",
    platform: "GeekBrains",
    category: "programming-web",
    url: "https://gb.ru/certificates/1781838",
    skills: ["Базовые алгоритмы", "Переменные и ветвления", "Архитектура кода"],
  },
  {
    id: "tech-geekbrains-wordpress",
    title: "Создание блога на WordPress",
    titleRu: "Разработка и настройка личного блога на CMS WordPress",
    issuer: "Образовательная платформа GeekBrains",
    platform: "GeekBrains",
    category: "programming-web",
    url: "https://gb.ru/certificates/1741856",
    skills: ["WordPress", "Темы и плагины", "SEO-структура блога"],
  },

  // -------------------------------------------------------------
  // 3. МАРКЕТИНГ, АНАЛИТИКА & ДИЗАЙН (marketing-design)
  // -------------------------------------------------------------
  {
    id: "mkt-yandex-metrika",
    title: "Специалист по Яндекс.Метрике",
    titleRu: "Официальный сертификат эксперта по Яндекс.Метрике",
    issuer: "Yandex",
    platform: "Yandex",
    category: "marketing-design",
    url: "https://yandex.ru/adv/expert/certificate/pdf/7upA9u4bbp/229516",
    isFlagship: true,
    skills: ["Веб-аналитика", "Настройка целей", "Когортный анализ", "Юзабилити"],
  },
  {
    id: "mkt-yandex-direct",
    title: "Специалист по Яндекс.Директу",
    titleRu: "Официальный сертификат по контекстной рекламе Яндекс.Директ",
    issuer: "Yandex",
    platform: "Yandex",
    category: "marketing-design",
    url: "https://yandex.ru/adv/expert/certificate/pdf/7upA9u4bbp/229799",
    isFlagship: true,
    skills: ["Контекстная реклама", "Семантическое ядро", "Оптимизация CPA"],
  },
  {
    id: "mkt-google-analytics",
    title: "Google Analytics for Beginners",
    titleRu: "Курс по Google Аналитике для начинающих",
    issuer: "Google Analytics Academy",
    platform: "Google",
    category: "marketing-design",
    url: "https://analytics.google.com/analytics/academy/certificate/XUEKPmoPSEyKtCLIYr0lvA",
    isFlagship: true,
    skills: ["Google Analytics", "Traffic Attribution", "Funnel Tracking"],
  },
  {
    id: "mkt-google-display",
    title: "Сертификация по контекстно-медийной сети Google Рекламы",
    titleRu: "Google Display Ads Certification",
    issuer: "Skillshop Google",
    platform: "Google",
    category: "marketing-design",
    url: "https://skillshop.exceedlms.com/student/award/mp2sjREHzwnT5czTWYwwznFg",
    skills: ["Google Ads", "Display Campaigns", "Smart Bidding"],
  },
  {
    id: "mkt-google-measurement",
    title: "Сертификация по оценке эффективности объявлений в Google Рекламе",
    titleRu: "Google Ads Measurement Certification",
    issuer: "Skillshop Google",
    platform: "Google",
    category: "marketing-design",
    url: "https://skillshop.exceedlms.com/student/award/5QxLX9bDSCPCxi4Qrs5U3kdg",
    skills: ["Ad ROI", "Attribution Modeling", "Conversion Tracking"],
  },
  {
    id: "mkt-monterrey-marketing-spec",
    title: "Marketing digital y sus análisis basado en datos",
    titleRu: "Профессиональный сертификат: Цифровой маркетинг и аналитика данных",
    issuer: "Tecnológico de Monterrey",
    platform: "edX",
    category: "marketing-design",
    url: "https://credentials.edx.org/credentials/cbeaa185bbf64a14af9d4667d9342a1a/",
    isFlagship: true,
    isSpecialization: true,
    skills: ["Data-driven Marketing", "Customer Engagement", "Digital Commerce"],
  },
  {
    id: "mkt-dartmouth-retail-spec",
    title: "Retail and Omnichannel Management Professional Certificate",
    titleRu: "Профессиональный сертификат: Розничная торговля и омниканальное управление",
    issuer: "Dartmouth College (Дартмут Колледж)",
    platform: "edX",
    category: "marketing-design",
    url: "https://credentials.edx.org/credentials/dde667d0ecbd4f1584191ce17cd40cc8/",
    isFlagship: true,
    skills: ["Omnichannel Strategy", "Retail Economics", "Supply Chain Integration"],
  },
  {
    id: "mkt-netology-smm",
    title: "Старт в SMM",
    titleRu: "Продвижение и контент-маркетинг в социальных сетях",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/df7664e017156618f0d33940210309e7",
    skills: ["SMM", "Контент-план", "Комьюнити-менеджмент"],
  },
  {
    id: "mkt-netology-marketing-intro",
    title: "Основы интернет-маркетинга: старт в профессии",
    titleRu: "Базовые каналы привлечения трафика и воронки продаж",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/0b3177bac41f2f726278df8bd6b49920",
    skills: ["Customer Journey", "CPA/CPC", "Лидогенерация"],
  },
  {
    id: "mkt-netology-content",
    title: "Как создавать контент для бизнеса",
    titleRu: "Сторителлинг, коммерческий копирайтинг и визуальный контент",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/094cb1adba510d532d31fbec3bd071a5",
    skills: ["Бизнес-контент", "Копирайтинг", "Tone of Voice"],
  },
  {
    id: "mkt-netology-photoshop",
    title: "Основы Adobe Photoshop",
    titleRu: "Обработка изображений, ретушь и слои в Photoshop",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/178af8330bacb6f0495e1ee2f8050e98",
    skills: ["Photoshop", "Ретушь", "Цветокоррекция"],
  },
  {
    id: "mkt-netology-canva",
    title: "Основы графического дизайна c Canva",
    titleRu: "Композиция, типографика и визуальные шаблоны",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/feec66e3c7a4be77d1df9c01e973e6c3",
    skills: ["Canva", "Композиция", "Баннеры"],
  },
  {
    id: "mkt-netology-figma",
    title: "Основы Figma",
    titleRu: "Интерфейсный дизайн, автолейауты и компоненты в Figma",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/523f26b40e1564f153b8751f537195d9",
    skills: ["Figma", "UI/UX", "Компоненты", "Сетки"],
  },
  {
    id: "mkt-geekbrains-collaging",
    title: "Adobe Photoshop. Коллажирование",
    titleRu: "Сложное многослойное коллажирование и арт-постпродакшн",
    issuer: "Образовательная платформа GeekBrains",
    platform: "GeekBrains",
    category: "marketing-design",
    url: "https://gb.ru/certificates/1739034",
    skills: ["Мэтт-пейнтинг", "Коллажирование", "Светотень"],
  },
  {
    id: "mkt-nsu-photo",
    title: "Основы фотографии",
    titleRu: "Экспозиция, ракурс и художественное восприятие кадра",
    issuer: "Новосибирский Государственный Университет (НГУ)",
    platform: "Coursera",
    category: "marketing-design",
    url: "https://www.coursera.org/account/accomplishments/verify/KSL6UJ9JMQPH",
    skills: ["Экспозиция", "Работа со светом", "Фотокомпозиция"],
  },
  {
    id: "mkt-michigan-cameras",
    title: "Cameras, Exposure, and Photography",
    titleRu: "Оптика, экспозиция и технические параметры камер",
    issuer: "Michigan State University",
    platform: "Coursera",
    category: "marketing-design",
    url: "https://www.coursera.org/account/accomplishments/verify/CUNZ2A45WDSQ",
    skills: ["Camera Sensors", "Optics", "Exposure Triangle"],
  },
  {
    id: "mkt-linkedin-mobile-photo",
    title: "Mobile Photography: Image Management",
    titleRu: "Мобильная съемка и каталогизация медиа-архивов",
    issuer: "LinkedIn Learning",
    platform: "Other",
    category: "marketing-design",
    url: "https://www.linkedin.com/learning/certificates/1d77433df65e9f765481bfc5c12e80abc8d36e809067ab7bf675975356456d72",
    skills: ["Mobile Shooting", "Asset Organization", "Lightroom Mobile"],
  },
  {
    id: "mkt-davidson-storytelling",
    title: "Applied Storytelling (Прикладной сторителлинг)",
    titleRu: "Драматургия, нарративные структуры и вовлечение аудитории",
    issuer: "Davidson College (Колледж Дэвидсон)",
    platform: "edX",
    category: "marketing-design",
    url: "https://courses.edx.org/certificates/04561f8555f44dfd89cab2453d27d564",
    skills: ["Storytelling", "Narrative Arc", "Brand Voice"],
  },
  {
    id: "mkt-netology-text",
    title: "Основы работы с текстом",
    titleRu: "Редактура, информационный стиль и структура статей",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/e16a7678bbd108378f9c2bb94c275478",
    skills: ["Инфостиль", "Редактура", "Структурирование смыслов"],
  },
  {
    id: "mkt-netology-marketplaces",
    title: "Маркетплейсы: как выбрать площадку для размещения",
    titleRu: "E-commerce воронки на Wildberries, Ozon и маркетплейсах",
    issuer: "Центр онлайн-образования «Нетология»",
    platform: "Netology",
    category: "marketing-design",
    url: "https://netology.ru/sharing/05398925ebf8660ed8771feac3ac27c9",
    skills: ["Маркетплейсы", "Инфографика карточек", "Unit-экономика"],
  },
  {
    id: "mkt-stepik-cpa",
    title: "Введение в арбитраж трафика и CPA маркетинг",
    titleRu: "Партнерский маркетинг, трекинг и монетизация трафика",
    issuer: "Stepik",
    platform: "Stepik",
    category: "marketing-design",
    url: "https://stepik.org/certificate/f86d278d7a021d93a3bcea5d7c43948d19ce6c06.pdf",
    skills: ["CPA Marketing", "Traffic Arbitrage", "Conversion Optimization"],
  },
  {
    id: "mkt-ratatype-speed",
    title: "Скорость слепой печати на русском языке: 225 зн/мин",
    titleRu: "Сертификат скорости клавиатурного набора",
    issuer: "Ratatype",
    platform: "Other",
    category: "marketing-design",
    url: "https://www.ratatype.ua/ru/u4108020/certificate/ru/",
    skills: ["Слепая печать", "225 знаков/мин", "Высокая скорость ввода"],
  },

  // -------------------------------------------------------------
  // 4. ЭНЕРГЕТИКА, ИНЖЕНЕРИЯ & LEAN (engineering-energy)
  // -------------------------------------------------------------
  {
    id: "eng-schneider-distributed",
    title: "Распределенная выработка электроэнергии",
    titleRu: "Schneider Electric: Распределенная энергетика и микросети",
    issuer: "Schneider Electric University",
    platform: "Other",
    category: "engineering-energy",
    url: "https://drive.google.com/file/d/1q0OMQZplTPgssJCBgqscERVhuzybVj6C/view?usp=sharing",
    isFlagship: true,
    skills: ["Microgrids", "Distributed Power", "Grid Stability"],
  },
  {
    id: "eng-delft-ev-spec",
    title: "Professional Certificate: Electric Cars",
    titleRu: "Профессиональный сертификат: Электромобили и зарядная инфраструктура",
    issuer: "Delft University of Technology (Делфтский технический университет)",
    platform: "edX",
    category: "engineering-energy",
    url: "https://credentials.edx.org/credentials/64f8bc65b91e412796f8341cfa862c4e/",
    isFlagship: true,
    isSpecialization: true,
    skills: ["EV Powertrains", "Battery Tech", "Charging Grids", "Policy"],
  },
  {
    id: "eng-buffalo-energy-spec",
    title: "Specialization: Energy Production, Distribution & Safety",
    titleRu: "Специализация: Производство, распределение и безопасность энергии",
    issuer: "University at Buffalo, The State University of New York",
    platform: "Coursera",
    category: "engineering-energy",
    url: "https://www.coursera.org/account/accomplishments/specialization/2DDQLSGG379M",
    isFlagship: true,
    isSpecialization: true,
    coursesCount: 4,
    skills: ["Electric Power Systems", "Natural Gas", "Utility Safety", "Grid Architecture"],
  },
  {
    id: "eng-imperial-clean-power",
    title: "Professional Certificate: Clean Power",
    titleRu: "Профессиональный сертификат: Возобновляемая и чистая энергия",
    issuer: "Imperial College London (Имперский колледж Лондона)",
    platform: "edX",
    category: "engineering-energy",
    url: "https://credentials.edx.org/credentials/19bb977705b34e36ae3a9a889ebdf454/",
    isFlagship: true,
    skills: ["Renewable Grids", "Solar/Wind Integration", "Decarbonization"],
  },
  {
    id: "eng-juran-six-sigma-spec",
    title: "Lean Six Sigma Black Belt Training & Certification Program",
    titleRu: "Программа сертификации Lean Six Sigma Black Belt",
    issuer: "Juran Institute",
    platform: "edX",
    category: "engineering-energy",
    url: "https://credentials.edx.org/credentials/bcd6b9b3eee44732936417fb7bc8230a/",
    isFlagship: true,
    isSpecialization: true,
    skills: ["Lean Six Sigma", "DMAIC", "Statistical Process Control", "Root Cause Analysis"],
  },
  {
    id: "eng-alison-electrical",
    title: "Diploma in Electrical Studies",
    titleRu: "Диплом в области электротехники и силовых сетей",
    issuer: "Alison - Empower Yourself",
    platform: "Other",
    category: "engineering-energy",
    url: "https://alison.com/certification/check/$2y$10$bjaGCk.2Rbji0caJgfSeRAnEzx26Iv67mCaVLlHWLgmsdBQ8qK",
    isFlagship: true,
    skills: ["Electrical Engineering", "Transformers", "Circuit Protection"],
  },
  {
    id: "eng-tum-lean-production",
    title: "Lean Production",
    titleRu: "Бережливое производство и оптимизация технологических цепочек",
    issuer: "Technical University of Munich (Мюнхенский технический университет)",
    platform: "edX",
    category: "engineering-energy",
    url: "https://courses.edx.org/certificates/99ef3adf9b5f49738c900001ff0c33ec",
    skills: ["5S", "Kaizen", "Just-in-Time", "Value Stream Mapping"],
  },
  {
    id: "eng-nus-electricity-dist",
    title: "Electricity Distribution & Switching Circuits",
    titleRu: "Распределение электроэнергии и коммутационные цепи",
    issuer: "The National University of Singapore (NUS)",
    platform: "edX",
    category: "engineering-energy",
    url: "https://courses.edx.org/certificates/a5a5795c1d69429c837870ee32f196cc",
    skills: ["Switching Circuits", "Power Flow", "Substation Automation"],
  },
  {
    id: "eng-alaska-microgrids",
    title: "Foundations of Microgrids",
    titleRu: "Основы автономных и изолированных микросетей",
    issuer: "University of Alaska Fairbanks",
    platform: "edX",
    category: "engineering-energy",
    url: "https://courses.edx.org/certificates/b37d5e99122f47d29967ffa16d8d95ab",
    skills: ["Microgrids", "Diesel-Renewable Hybrid", "Energy Storage"],
  },
  {
    id: "eng-colorado-utilities",
    title: "Electric Utilities Fundamentals and Future",
    titleRu: "Основы и будущее коммунальной электроэнергетики",
    issuer: "University of Colorado",
    platform: "Coursera",
    category: "engineering-energy",
    url: "https://www.coursera.org/account/accomplishments/verify/JA62T9WPYAEU",
    skills: ["Utility Grids", "Smart Metering", "Energy Markets"],
  },
  {
    id: "eng-grundfos-controls",
    title: "The Monitoring and Controls Learning Track",
    titleRu: "Курс обучения мониторингу и промышленному контролю",
    issuer: "Grundfos Ecademy",
    platform: "Other",
    category: "engineering-energy",
    url: "https://drive.google.com/file/d/1x92iTrS21tdYdqm4Fr60BBMLj0xnPjcG/view?usp=sharing",
    skills: ["Pump Automation", "Telemetry", "Industrial SCADA"],
  },
  {
    id: "eng-lektorium-drones",
    title: "Дроны: Автономные беспилотные воздушные системы",
    titleRu: "Автономная навигация, телеметрия и управление БПЛА",
    issuer: "Лекториум",
    platform: "Other",
    category: "engineering-energy",
    url: "https://mooc.lektorium.tv/certificates/bc8aad2aa07b4200a502d023de34396e",
    skills: ["Беспилотники", "Полетные контроллеры", "Автономные миссии"],
  },
  {
    id: "eng-fefu-lean",
    title: "Бережливое производство. Базовый курс",
    titleRu: "Оптимизация производственных процессов и сокращение потерь",
    issuer: "Дальневосточный федеральный университет (ДВФУ)",
    platform: "Stepik",
    category: "engineering-energy",
    url: "https://stepik.org/certificate/eaf01dd531a2c41a3f50ab760cdd0bab83397c92.pdf",
    skills: ["Бережливое производство", "Кайдзен", "5S", "Оптимизация потерь"],
  },
  {
    id: "eng-zhilkom-fire-safety",
    title: "Обучение мерам пожарной безопасности Министерства ЖКХ РБ",
    titleRu: "Пожарно-технический минимум на опасных производственных объектах",
    issuer: "ГЦПК «ЖИЛКОМ»",
    platform: "Other",
    category: "engineering-energy",
    url: "https://drive.google.com/file/d/1emfvKZQDFBfLYrncmhwnFw6GJRm6DS95/view?usp=sharing",
    skills: ["Пожарная безопасность", "Охрана труда", "Техника безопасности"],
  },

  // -------------------------------------------------------------
  // 5. МЕНЕДЖМЕНТ, ЛИДЕРСТВО & ПРАВО (management-leadership)
  // -------------------------------------------------------------
  {
    id: "mgmt-harvard-remote-spec",
    title: "Professional Certificate: Leading in a Remote Environment",
    titleRu: "Профессиональный сертификат Гарварда: Лидерство в удаленной среде",
    issuer: "Harvard University (Гарвардский университет)",
    platform: "Harvard",
    category: "management-leadership",
    url: "https://credentials.edx.org/credentials/b29ff999c4e34861b54c24b7e1e3f3a3/",
    isFlagship: true,
    isSpecialization: true,
    skills: ["Remote Leadership", "Team Trust", "Digital Culture", "Async Communication"],
  },
  {
    id: "mgmt-harvard-leadership",
    title: "Exercising Leadership: Foundational Principles",
    titleRu: "Лидерство: Основополагающие принципы преодоления кризисов",
    issuer: "Harvard University",
    platform: "Harvard",
    category: "management-leadership",
    url: "https://courses.edx.org/certificates/abdb4cff5eb047428d758d5b50f9366a",
    skills: ["Adaptive Leadership", "Crisis Navigation", "Stakeholder Alignment"],
  },
  {
    id: "mgmt-harvard-us-gov-series",
    title: "XSeries Program: U.S. Government & Public Policy",
    titleRu: "Программа сертификации: Конституционные основы и государственные институты",
    issuer: "Harvard University",
    platform: "Harvard",
    category: "management-leadership",
    url: "https://credentials.edx.org/credentials/d0f5caadf504449092ff57a72eed6a59/",
    isFlagship: true,
    isSpecialization: true,
    coursesCount: 4,
    skills: ["Institutional Analysis", "Public Policy", "Constitutional Law"],
  },
  {
    id: "mgmt-mit-emerging-future",
    title: "Leading From the Emerging Future",
    titleRu: "MIT: Лидерство из зарождающегося будущего (Theory U)",
    issuer: "Massachusetts Institute of Technology (MIT)",
    platform: "edX",
    category: "management-leadership",
    url: "https://courses.edx.org/certificates/31ae8c9d965c4a0b9dce8db43c2eafff",
    isFlagship: true,
    skills: ["Theory U", "Systems Thinking", "Transformational Change"],
  },
  {
    id: "mgmt-rit-leadership-spec",
    title: "Professional Certificate: Leadership Essentials",
    titleRu: "Профессиональная сертификация RIT: Основы лидерства",
    issuer: "Rochester Institute of Technology (RIT)",
    platform: "edX",
    category: "management-leadership",
    url: "https://credentials.edx.org/credentials/37b74b5973f34b29846554e451e956ed/",
    isFlagship: true,
    skills: ["Critical Thinking", "Problem Solving", "Team Collaboration"],
  },
  {
    id: "mgmt-stellenbosch-hr-spec",
    title: "Strategic Human Resources Management Professional Certificate",
    titleRu: "Профессиональный сертификат: Стратегический HR-менеджмент",
    issuer: "Stellenbosch University",
    platform: "edX",
    category: "management-leadership",
    url: "https://credentials.edx.org/credentials/b9c639dc5aba44c5a0e942687ca6eacd/",
    isFlagship: true,
    skills: ["Talent Management", "DEI Strategy", "Organizational Architecture"],
  },
  {
    id: "mgmt-cbs-mba",
    title: "Вводный курс MBA",
    titleRu: "Основы бизнес-администрирования и финансового планирования",
    issuer: "City Business School",
    platform: "Other",
    category: "management-leadership",
    url: "https://drive.google.com/file/d/1qnqTuACAEmDUIG6aOV7bh0645UPrlbTt/view?usp=sharing",
    isFlagship: true,
    skills: ["MBA Основы", "Операционный менеджмент", "Финансовые модели"],
  },
  {
    id: "mgmt-cbs-copenhagen",
    title: "Leadership in 21st Century Organizations",
    titleRu: "Лидерство в организациях 21 века",
    issuer: "Copenhagen Business School",
    platform: "Coursera",
    category: "management-leadership",
    url: "https://www.coursera.org/account/accomplishments/verify/ED5HTJRS66C5",
    skills: ["Decentralized Leadership", "Agile Organizations", "Network Management"],
  },
  {
    id: "mgmt-polyu-industry4",
    title: "Business Excellence in a knowledge-driven Industry 4.0 world",
    titleRu: "Профессиональный сертификат: Совершенствование бизнеса в эпоху Индустрии 4.0",
    issuer: "The Hong Kong Polytechnic University (PolyU)",
    platform: "edX",
    category: "management-leadership",
    url: "https://credentials.edx.org/credentials/d7fd8f6a35554de788ffb1217afb566a/",
    isFlagship: true,
    skills: ["Big Data in Business", "Knowledge Management", "Industry 4.0 Transformation"],
  },
  {
    id: "mgmt-jhu-principles",
    title: "Principles of Management",
    titleRu: "Фундаментальные принципы управления",
    issuer: "Johns Hopkins University",
    platform: "Coursera",
    category: "management-leadership",
    url: "https://www.coursera.org/account/accomplishments/verify/BUYF85Y8QQ2X",
    skills: ["Management Functions", "Delegation", "Resource Allocation"],
  },
  {
    id: "mgmt-unesco-anticipatory",
    title: "Anticipatory Governance: New ways of sense-making and navigating for uncertainty",
    titleRu: "ЮНЕСКО: Упреждающее управление в условиях неопределенности",
    issuer: "UNESCO (ЮНЕСКО)",
    platform: "Other",
    category: "management-leadership",
    url: "https://openlearning.unesco.org/certificates/e02437a7f6294b7d9fb09eb0695be874",
    isFlagship: true,
    skills: ["Futures Literacy", "Sense-making", "Strategic Foresight"],
  },
  {
    id: "mgmt-anahuac-eleadership",
    title: "E-Leadership: liderazgo en la Era Virtual",
    titleRu: "Профессиональный сертификат: Электронное лидерство в виртуальную эпоху",
    issuer: "Anahuac University Network",
    platform: "edX",
    category: "management-leadership",
    url: "https://credentials.edx.org/credentials/6ff342f3c0a340ef9d6dfbea40e6f0b0/",
    isFlagship: true,
    skills: ["Virtual Teams", "Digital Influence", "Cross-cultural Leadership"],
  },
  {
    id: "mgmt-nyif-risk-management",
    title: "Risk Management Professional Series",
    titleRu: "Управление рисками, стресс-тестирование и регулирование",
    issuer: "New York Institute of Finance (Нью-Йоркский финансовый институт)",
    platform: "edX",
    category: "management-leadership",
    url: "https://courses.edx.org/certificates/acda6754a74c49b69108ad2b4888cb5c",
    skills: ["Risk Identification", "Stress Testing", "Financial Derivatives"],
  },
  {
    id: "mgmt-columbia-civil-war",
    title: "The Civil War and Reconstruction XSeries Program",
    titleRu: "Программа сертификации Колумбийского университета: История институтов и государства",
    issuer: "Columbia University (Колумбийский университет)",
    platform: "edX",
    category: "management-leadership",
    url: "https://credentials.edx.org/credentials/2b69d31f6ee840fdbb693e50f29c5f3b/",
    isFlagship: true,
    skills: ["Historical Analysis", "Institutional Evolution", "Constitutional Frameworks"],
  },
  {
    id: "mgmt-ranepa-digital",
    title: "Эпоха цифрового развития: основы цифровой трансформации",
    titleRu: "Цифровая трансформация и платформенная экономика",
    issuer: "РАНХиГС",
    platform: "Stepik",
    category: "management-leadership",
    url: "https://stepik.org/certificate/7a566dc6773cb46951113f2f6b412e559e5a9b41.pdf",
    skills: ["Цифровая трансформация", "Платформенная экономика", "Data-driven Governance"],
  },

  // -------------------------------------------------------------
  // 6. ООН, ВОЗ, МЕДИЦИНА & БЕЗОПАСНОСТЬ (global-health-safety)
  // -------------------------------------------------------------
  {
    id: "global-undss-bsafe",
    title: "BSAFE — Безопасность персонала ООН",
    titleRu: "Официальный сертификат безопасности Департамента охраны ООН (UNDSS)",
    issuer: "United Nations Department of Safety and Security (UNDSS)",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/10Sa6991ynSNZwMnss0l0qbGY0hpdjKZU/view?usp=sharing",
    isFlagship: true,
    skills: ["UN Security Protocols", "Threat Assessment", "Crisis Preparedness"],
  },
  {
    id: "global-unv-program",
    title: "Программа добровольцев ООН (United Nations Volunteers — 8 сертификатов)",
    titleRu: "Комплексная программа подготовки волонтеров ООН",
    issuer: "United Nations Volunteers (UNV)",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/12i5EQjNOLdZC1IjwMImvgYB96bc2SfHN/view?usp=sharing",
    isFlagship: true,
    isSpecialization: true,
    coursesCount: 8,
    skills: ["UN SDG Goals", "Humanitarian Action", "Cross-Cultural Operations"],
  },
  {
    id: "global-unssc-human-security",
    title: "The Human Security Approach: From Principles to Practice",
    titleRu: "Колледж системного персонала ООН (UNSSC): Концепция безопасности человека",
    issuer: "UNSSC (United Nations System Staff College)",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1evcWM9B9etsiJQbzdXhlBOOYmfFoZdg1/view?usp=sharing",
    isFlagship: true,
    skills: ["Human Security", "UN Frameworks", "Sustainable Development"],
  },
  {
    id: "global-who-covid19",
    title: "Введение: COVID-19 способы диагностики, профилактики и контроля",
    titleRu: "Официальный сертификат Всемирной организации здравоохранения (ВОЗ)",
    issuer: "World Health Organization (ВОЗ)",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://openwho.org/verify/xeheb-pakul-cenac-palud-ryzuv",
    isFlagship: true,
    skills: ["Epidemiology", "Infection Control", "WHO Response Frameworks"],
  },
  {
    id: "global-fema-outbreak",
    title: "Response Considerations During an Outbreak or Pandemic",
    titleRu: "Рекомендации по реагированию на вспышки и пандемии (FEMA США)",
    issuer: "FEMA / The Center for Domestic Preparedness (США)",
    platform: "Other",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1TTOKHwwOqz9pgnJvZ0dk1A6S8moqnOdc/view?usp=sharing",
    isFlagship: true,
    skills: ["Emergency Operations", "Pandemic Mitigation", "Domestic Preparedness"],
  },
  {
    id: "global-jhu-contact-tracing",
    title: "COVID-19 Contact Tracing",
    titleRu: "Отслеживание контактов и эпидемиологический протокол",
    issuer: "Johns Hopkins University (Университет Джонса Хопкинса)",
    platform: "Coursera",
    category: "global-health-safety",
    url: "https://www.coursera.org/account/accomplishments/certificate/SZPV7LK3F8SB",
    isFlagship: true,
    skills: ["Epidemiology", "Contact Tracing", "Public Health Protocols"],
  },
  {
    id: "global-jhu-dementia",
    title: "Living with Dementia: Impact on Individuals, Caregivers, Communities",
    titleRu: "Жизнь с деменцией: нейрокогнитивные нарушения и уход",
    issuer: "Johns Hopkins University",
    platform: "Coursera",
    category: "global-health-safety",
    url: "https://www.coursera.org/account/accomplishments/verify/FKKF532X7JH5",
    skills: ["Neurodegenerative Conditions", "MedTech Support", "Patient Care"],
  },
  {
    id: "global-stanford-covid",
    title: "COVID-19 Training for Healthcare Workers",
    titleRu: "Клинический тренинг для медработников от Stanford Medicine",
    issuer: "Stanford Online (Стэнфордский университет)",
    platform: "Coursera",
    category: "global-health-safety",
    url: "https://www.coursera.org/account/accomplishments/certificate/4LRWJ6N9D873",
    isFlagship: true,
    skills: ["Critical Care", "Airway Management", "Triage Protocols"],
  },
  {
    id: "global-unicef-gender",
    title: "Gender Equality in Preparedness and Humanitarian Action",
    titleRu: "Гендерное равенство в гуманитарных миссиях ЮНИСЕФ",
    issuer: "UNICEF (ЮНИСЕФ)",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1GU_bzH6V63qpbjLpVP567zOLeduVNr1b/view?usp=sharing",
    skills: ["Humanitarian Standards", "Child Protection", "Emergency Welfare"],
  },
  {
    id: "global-iaea-safeguards",
    title: "Basic Training Course on IAEA Safeguards",
    titleRu: "Базовый учебный курс по гарантиям МАГАТЭ",
    issuer: "IAEA - International Atomic Energy Agency (МАГАТЭ)",
    platform: "Other",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1dkxkFeta5vOuQUNFgmBZ2V40jp4IEj1t/view?usp=sharing",
    isFlagship: true,
    skills: ["Nuclear Safeguards", "Non-Proliferation", "Verification Procedures"],
  },
  {
    id: "global-worldbank-esf",
    title: "Социально-экологические принципы Всемирного банка",
    titleRu: "World Bank Environmental & Social Framework",
    issuer: "World Bank Group (Всемирный банк)",
    platform: "Other",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1AxviTbtydHY-uAMq5BKSEPwFCE__-d-_/view?usp=sharing",
    skills: ["ESG Standards", "Environmental Assessment", "Project Sustainability"],
  },
  {
    id: "global-un-ocha-osocc",
    title: "OSOCC Awareness Course",
    titleRu: "Управление ООН по координации гуманитарных вопросов (UN OCHA)",
    issuer: "UN OCHA",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1bxzrnpqRoJIfgVVKH9f-d41DkSgUq73C/view?usp=sharing",
    skills: ["Disaster Response Coordination", "Field Logistics", "UN Clusters"],
  },
  {
    id: "global-unoda-cyber-diplomacy",
    title: "Cyber Diplomacy (Кибердипломатия)",
    titleRu: "Управление по вопросам разоружения ООН (UNODA)",
    issuer: "United Nations Office for Disarmament Affairs (UNODA)",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1wlW__FbLCdf-UDIh8I6aa_8k4hvt2V--/view?usp=sharing",
    skills: ["Cyber Warfare Norms", "International Cyber Stability", "Threat Governance"],
  },
  {
    id: "global-itcilo-fire-safety",
    title: "Essentials of fire safety inspections",
    titleRu: "Основы инспекций пожарной безопасности Учебного центра МОТ (ITCILO)",
    issuer: "International Training Centre of the ILO (ITCILO)",
    platform: "Other",
    category: "global-health-safety",
    url: "https://credentials.itcilo.org/f5ef6288-98cb-4ec4-8b68-f6d59626ecb3#gs.48c69j",
    skills: ["Fire Risk Assessment", "Industrial Auditing", "Evacuation Planning"],
  },
  {
    id: "global-stepik-cpr",
    title: "Первая помощь при остановке сердца (базовая реанимация)",
    titleRu: "Крымский симуляционный центр экстренной медицины",
    issuer: "Симуляционный центр экстренной медицины",
    platform: "Stepik",
    category: "global-health-safety",
    url: "https://stepik.org/certificate/2ee0cbc5e4898ced5c0d9cb9ceb7e7a66cb54f68.pdf",
    skills: ["СЛР (CPR)", "Дефибрилляция (AED)", "Экстренная доврачебная помощь"],
  },
  {
    id: "global-un-cclearn-climate",
    title: "Human Health and Climate Change",
    titleRu: "Влияние климатических изменений на здоровье человека",
    issuer: "UN CC:Learn (Обучение ООН)",
    platform: "UN / WHO",
    category: "global-health-safety",
    url: "https://drive.google.com/file/d/1SriO0XirYRwX3j6sx2NMRYCa-I8McjU0/view?usp=sharing",
    skills: ["Climate Resilience", "Public Health", "Environmental Epidemiology"],
  },
  {
    id: "global-wageningen-tourism-spec",
    title: "Professional Certificate: Tourism in Transition",
    titleRu: "Профессиональный сертификат: Устойчивое развитие туризма и климат",
    issuer: "Wageningen University & Research",
    platform: "edX",
    category: "global-health-safety",
    url: "https://credentials.edx.org/credentials/616eef1d5b0143b585757e18ea5eb2da/",
    isFlagship: true,
    isSpecialization: true,
    skills: ["Sustainable Tourism", "Climate Adaptation", "Ecosystem Management"],
  },
  {
    id: "global-colorado-animals-spec",
    title: "Specialization: Animals and Society",
    titleRu: "Специализация: Животные, общество и этические институты",
    issuer: "University of Colorado Boulder",
    platform: "Coursera",
    category: "global-health-safety",
    url: "https://www.coursera.org/account/accomplishments/specialization/JGNDB9Q9HQWA",
    isFlagship: true,
    isSpecialization: true,
    coursesCount: 3,
    skills: ["Bioethics", "Animal Welfare", "Institutional Policy"],
  },
];
